name: Run Tests

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: 'lts' # Use the latest LTS version of Julia
    
      - name: Cache dependencies
        uses: julia-actions/cache@v2
      - name: Build package
        uses: julia-actions/julia-buildpkg@v1
      - name: Run /test/runtests.jl
        uses: julia-actions/julia-runtest@v1
